"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { Group, Mesh, Material } from "three";


// This is needed for JSX.IntrinsicElements in Next.js
import type {} from "react";

interface PlanetProps {
  [key: string]: any;
}

export function Planet(props: PlanetProps) {
  const shapeContainer = useRef<Group>(null);
  const spheresContainer = useRef<Group>(null);
  const ringContainer = useRef<Mesh>(null);
  
  // Use type assertion with unknown first to avoid TypeScript errors
  const gltf = useGLTF("/models/Planet.glb");
  const { nodes, materials } = gltf as unknown as {
    nodes: {
      Sphere: Mesh;
      Sphere2: Mesh;
      Ring: Mesh;
    };
    materials: {
      ["Material.002"]: Material;
      ["Material.001"]: Material;
    };
  };

  useGSAP(() => {
    const tl = gsap.timeline();
    
    if (shapeContainer.current) {
      tl.from(shapeContainer.current.position, {
        y: 5,
        duration: 3,
        ease: "circ.out",
      });
    }
    
    if (spheresContainer.current) {
      tl.from(
        spheresContainer.current.rotation,
        {
          x: 0,
          y: Math.PI,
          z: -Math.PI,
          duration: 10,
          ease: "power1.inOut",
        },
        "-=25%"
      );
    }
    
    if (ringContainer.current) {
      tl.from(
        ringContainer.current.rotation,
        {
          x: 0.8,
          y: 0,
          z: 0,
          duration: 10,
          ease: "power1.inOut",
        },
        "<"
      );
    }
  }, []);

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={spheresContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.001"]}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials["Material.001"]}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");